global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#alexander_belkin'
