version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db 
  ui:
    image: ${DOCKER_HUB_USER}/ui:${UI_VERSION}
    ports:
      - 9292:${UI_PORT}/tcp
    networks:
      - front_net
  post:
    image: ${DOCKER_HUB_USER}/post:${POST_VERSION}
    networks:
      - back_net
      - front_net
  comment:
    image: ${DOCKER_HUB_USER}/comment:${COMMENT_VERSION}
    networks:
      - back_net
      - front_net
      
volumes:
  post_db:
  prometheus_data:

networks:
  back_net:
    ipam:
      config:
        - subnet: 10.0.2.0/24
  front_net:
    ipam:
      config:
        - subnet: 10.0.1.0/24
